// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEslOakhR--iqxqki9B1yTyWqdWqO7KU',
    appId: '1:527656952959:android:079b21971708f1d6540b4a',
    messagingSenderId: '527656952959',
    projectId: 'unitalk-cae71',
    storageBucket: 'unitalk-cae71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-_Zw7FJToI62-2H0INF7G4FgOTvjIJgc',
    appId: '1:527656952959:ios:513cec64737d13e0540b4a',
    messagingSenderId: '527656952959',
    projectId: 'unitalk-cae71',
    storageBucket: 'unitalk-cae71.appspot.com',
    androidClientId: '527656952959-okh9ur6fl4slbu31uqoac57cv5jiduc4.apps.googleusercontent.com',
    iosClientId: '527656952959-1mcfcjf8lra2v2j8jtb1nnbuvtb1vvnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitalk',
  );

}